include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_unnecessary_containers: true
    - prefer_const_constructors: true
    - avoid_warnings: true
    - avoid_infos_and_warnings: true
